- hosts: all
  gather_facts: no
  tasks:
    - authorized_key:
       user: "{{ ansible_user }}"
       state: present
       key: "{{ lookup('file', ansible_ssh_private_key_file | default('~/.ssh/id_rsa.pub')) }}"
